"""add_locale_to_games

Revision ID: 37902166f8c9
Revises: fa25ee438904
Create Date: 2026-01-07 22:44:54.345914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37902166f8c9'
down_revision = 'fa25ee438904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('locale', sa.String(), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'locale')
    # ### end Alembic commands ###
