"""Initial tables

Revision ID: fa25ee438904
Revises: 
Create Date: 2025-12-22 18:13:19.741911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa25ee438904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('white_player_id', sa.BIGINT(), nullable=False),
    sa.Column('black_player_id', sa.BIGINT(), nullable=True),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('board_state', sa.JSON(), nullable=False),
    sa.Column('current_turn', sa.Enum('WHITE', 'BLACK', name='playercolor'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FINISHED', 'CANCELLED', name='gamestatus'), nullable=False),
    sa.Column('winner_id', sa.BIGINT(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.BIGINT(), nullable=False),
    sa.Column('from_position', sa.String(), nullable=False),
    sa.Column('to_position', sa.String(), nullable=False),
    sa.Column('captured_positions', sa.JSON(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
